### ISSUE TITLE
就不能搞个完整版的demo吗？下了好几个都是缺文件

### ISSUE THREAD

**Issue by mengday** [easemob/sdkdemoapp3.0_ios#108]
http://www.easemob.com/download/im 这个也不行啊

**Comment by lizilong1989** [comment]
@mengday http://www.easemob.com/download/im 确定这个地址的也不可运行吗?

**Comment by Mark-SS** [comment]
@lizilong1989 确定，这个地址里面点击demo下载 也是跳转到github。

**Comment by Mark-SS** [comment]
@lizilong1989 如果demo依赖sdk或者其它库，可以考虑用pod或者 git submodule 子模块 会方便很多。
