### ISSUE TITLE
我的也是找不到头文件，clean好多次之后还是这样

### ISSUE THREAD

**Issue by Doramical** [easemob/sdkdemoapp3.0_ios#11]
ChatDemo-UI3.0/ChatDemo-UI3.0/ChatDemo-UI3.0-Prefix.pch:21:13: 'UIViewController+DismissKeyboard.h' file not found

**Comment by jinguang1** [comment]
hello!

**Comment by jinguang1** [comment]
are you there?

**Comment by jinguang1** [comment]
hi doramical
