### ISSUE TITLE
Error installing FirebaseAnalytics in cocoaPods

### ISSUE THREAD

**Issue by litt1e-p** [easemob/sdkdemoapp3.0_ios#111]
hi, I cloned the git lib with branch "USDemo", and I install cocoapods via Podfile, every pod installed successfully but FirebaseAnalytics, it shows an error `Failed to connect to www.gstatic.com`, at last, I found that `www.gstatic.com` can not open even in my browser, this website reponsed with `404 not found`. what is wrong with it?

**Comment by lizilong1989** [comment]
@litt1e-p USDemo has been deprecated,please use https://github.com/HyphenateInc/Hyphenate-Demo-iOS
