### ISSUE TITLE
现在的DEMO  谁开发的？开除他

### ISSUE THREAD

**Issue by liuligui** [easemob/sdkdemoapp3.0_ios#142]
全是少这个少那个，有什么参考价值？

**Comment by liuligui** [comment]
真实神经病

**Comment by lizilong1989** [comment]
可以去官网直接下载完整版，github中不包含sdk和easeui

**Comment by CrazyCoderShi** [comment]
说真的Demo的代码写的真心不咋地,各个模块间的耦合太大,而且还依赖一些三方库,这点儿有点儿不能忍

**Comment by xieyajie** [comment]
我开个开源demo，大家一起写怎么样？楼上2位要不要报名？

**Comment by jasonhe88** [comment]
从3.2.3到3.2.0都试了， 编译都不能成功， 缺这个缺哪个， 这就敢release了？简直了

**Comment by jasonhe88** [comment]
官网下的也不能编译成功

**Comment by xieyajie** [comment]
readme里标注了：此demo依赖于easeui库，clone代码时需要把easeui也下载下来，easeui的分支情况同上分支说明，easeui的github地址为https://github.com/easemob/easeui_ios。

如果想要直接可以用的，可以去官网直接下载完整版，github中不包含sdk和easeui。

**Comment by jasonhe88** [comment]
用cocopad安装过依赖了，，，另外， 官网的简版demo编译通不过

**Comment by lizilong1989** [comment]
@jasonhe88 https://github.com/easemob/sdkdemoapp3.0_ios/tree/3.2.3 用这个试一下

**Comment by CCBrother** [comment]
官网下载的最新的demo，也都是报错，太浪费时间了

**Comment by xieyajie** [comment]
@CCBrother 请问是什么错误呢？官网demo需要配置自己的证书

**Comment by CCBrother** [comment]
<img width="871" alt="default" src="https://user-images.githubusercontent.com/14049399/44074425-1a5d3b8e-9fcb-11e8-8324-c7a491ba60ef.png">
<img width="874" alt="default" src="https://user-images.githubusercontent.com/14049399/44074430-23e0c16c-9fcb-11e8-88aa-f12800ee1ab2.png">

**Comment by CCBrother** [comment]
什么证书?

**Comment by CCBrother** [comment]
为什么关闭错误截图？
