### ISSUE TITLE
iOS10 推送userinfo为空字典？

### ISSUE THREAD

**Issue by singno** [easemob/sdkdemoapp3.0_ios#218]
如题，无法获取到有用的userinfo信息

@available(iOS 10.0, *)
    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        print(response.notification.request.content.userInfo)
        completionHandler()
    }

**Comment by xieyajie** [comment]
@singno 请问您的问题解决了吗？
