### ISSUE TITLE
执行pod install 之后不能运行，还是好多错误

### ISSUE THREAD

**Issue by XiMingJun** [easemob/sdkdemoapp3.0_ios#227]

**Comment by lizilong1989** [comment]
你用的是哪个branch，具体的报错信息是什么？

**Comment by XiMingJun** [comment]
就github主页那个分支 sdk3.x,你自己下下来一份，执行一遍就知道了。

**Comment by lizilong1989** [comment]
@XiMingJun 感谢您的反馈，现在pod update应该就可以了

**Comment by XiMingJun** [comment]
ShareFilesViewController.m里边第90行，那个sendFileMessageWith: 方法是哪来的，这是编译第一个明显的bug.

**Comment by lizilong1989** [comment]
@XiMingJun 嗯，我这边遇到的错误跟你那边不太一样，而且我这边有一些本地的东西，现在应该是可以了
