### ISSUE TITLE
最新demo报错，你们都不检查下就发布？？？

### ISSUE THREAD

**Issue by CCBrother** [easemob/sdkdemoapp3.0_ios#264]
<img width="857" alt="default" src="https://user-images.githubusercontent.com/14049399/44074320-afadb610-9fca-11e8-9dac-acade4caf674.png">

**Comment by CCBrother** [comment]
<img width="871" alt="default" src="https://user-images.githubusercontent.com/14049399/44074352-d0f0f922-9fca-11e8-8120-68d050d3ccb2.png">

**Comment by xieyajie** [comment]
@CCBrother 我下载了官方demo，可以直接运行，没有问题啊[](url)

**Comment by CCBrother** [comment]
那你可以传给我吗？

**Comment by xieyajie** [comment]
@CCBrother 我就是在官网下载后，直接运行的，没进行其他操作。github上我也没法传给你啊

**Comment by CCBrother** [comment]
你是下载最新的吗？我pod install之后运行，就是上面截图的错误了，都无从下手！395627474@qq.com，能麻烦发一份给我的吗？谢谢！下载了好多份，都不行。。。

**Comment by xieyajie** [comment]
官网的源码是拿来直接运行的，如果你用pod，需要重新配置demo中的各种库和头文件的引用

**Comment by CCBrother** [comment]
还要重新配置demo中的各种库和头文件啊？哥们，你能传一份给我吗？

**Comment by CCBrother** [comment]
不能传的话，你帮忙看看上面的问题怎么解决？

**Comment by xieyajie** [comment]
您稍等会，正在看呢

**Comment by CCBrother** [comment]
<img width="488" alt="default" src="https://user-images.githubusercontent.com/14049399/44075444-62300dfc-9fcf-11e8-8ec2-1d38327ed933.png">
我又去官网重新下载了，不pod了，直接打开project，现在居然可以了，早上都不可以，所以我才去pod。如果不用pod的话，podfile文件就不要上传了，不然以为还要pod install！还是谢谢你了~

**Comment by xieyajie** [comment]
不客气，官方源码直接运行是可以的。如果使用pod，需要将demo源码中对EaseUI和Hyphenate.framework的依赖都去掉之后，再进行pod操作就可以了。我刚才更新了下EaseUI的pod地址，应该是没有什么问题的。
很感谢您的反馈，辛苦辛苦

**Comment by CCBrother** [comment]
都是一样为了工作，谢谢谢谢~
