### ISSUE TITLE
Demo 中 Prefix 文件找不到各种 header

### ISSUE THREAD

**Issue by gztchan** [easemob/sdkdemoapp3.0_ios#6]

**Comment by githubzhaoliang** [comment]
不知道是指什么方面？有具体错误信息吗？

**Comment by allabttony** [comment]
反应很快！
Demo 中 的 prefix 文件

```objc
#ifdef __OBJC__
    #import <UIKit/UIKit.h>
    #import <Foundation/Foundation.h>

    #import "ChatDemoUIDefine.h"
    #import "EMAlertView.h"
    #import "TTGlobalUICommon.h"
//    #import "UIViewController+HUD.h"
    #import "UIViewController+DismissKeyboard.h"
    #import "NSString+Valid.h"
    #import "EaseUI.h"

    #import "EaseMob.h"

#endif
```
这里全部都显示找不到 h 文件，我是 Xocde 7

**Comment by lizilong1989** [comment]
Demo3.0需要集成IM SDK和EaseUI(UI库),具体集成文档在:
http://docs.easemob.com/doku.php?id=start:300iosclientintegration:140easeuiuseguide

**Comment by lizilong1989** [comment]
@allabttony Demo3.0需要集成IM SDK和EaseUI(UI库),具体集成文档在:
http://docs.easemob.com/doku.php?id=start:300iosclientintegration:140easeuiuseguide

**Comment by heqichang** [comment]
![essemob-bug](https://cloud.githubusercontent.com/assets/717699/15249656/4b9bdce2-1953-11e6-9ad5-603d1c142707.png)

下面那几个都 not found

    #import "UIViewController+DismissKeyboard.h"
    #import "NSString+Valid.h"
    #import "EaseUI.h"

    #import "EaseMob.h"
