### ISSUE TITLE
iOS客户顿接受离线消息，UI刷新卡顿严重

### ISSUE THREAD

**Issue by BeatsKitano** [easemob/sdkdemoapp3.0_ios#87]
客户端接收离线消息时，在用户量较少的情况小，很难发现问题。倘若进行理性暴力测试，一个客户端直接发300条消息给一个离线的客户端，当离线客户端启动时，服务器可能将这一大批数据直接传给iOS客户端，数据处理频繁，主线程UI刷新频繁，即使是异步处理数据，那么对UI的刷新要求也会高于60FPS，导致卡顿。希望优化。

**Comment by githubzhaoliang** [comment]
多谢反馈，我们有计划调整服务器一次下发的消息数量，希望能尽快更新优化这个问题。
